apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: payment-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: SERVICE_ACCESS_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: service-access-token
            - name: AUTH_SERVICE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: auth-service-base-url
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5001
      nodePort: 30101
